#!/bin/bash
#
# setupwrf - Sets up the current directory to run WRF
#

# Links to data files
ln -s @DATADIR@/WRF/run/* .

# Default namelist.input if it doesn't exist
[ ! -f namelist.input ] && cp -a @DATADIR@/WRF/test/em_real/namelist.input .

exit 0
